services:
  - type: web
    name: taskmanage-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: run
      - key: JWT_SECRET
        scope: run
      - key: NODE_ENV
        value: production

  - type: web
    name: taskmanage-frontend
    env: node
    plan: free
    rootDir: frontend/client
    buildCommand: npm install && CI=false npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        scope: run
      - key: NODE_ENV
        value: production
      - key: CI
        value: "false"
